version: '3.7'
services:
        mysql:
                image: mysql:8.0.16
                env_file:
                        - .env
                ports:
                        - ${DB_HOST}:${DB_PORT}:3306
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - ./tmp/mysql:/var/lib/mysql
                        # - ./migrations:/docker-entrypoint-initdb.d
                environment:
                        - MYSQL_ROOT_PASSWORD=123456
                        - MYSQL_USER=${DB_USER}
                        - MYSQL_PASSWORD=${DB_PASS}
                        - MYSQL_DATABASE=${DB_NAME}
        postgresql:
                image: postgres:11.3-alpine
                env_file:
                        - .env
                ports:
                        - ${DB_HOST}:5432:5432
                volumes:
                        - ./tmp/postgresql:/var/lib/postgresql/data
                environment:
                        - POSTGRES_USER=${DB_USER}
                        - POSTGRES_PASSWORD=${DB_PASS}
                        - POSTGRES_DB=${DB_NAME}
